application: eighty-friends
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: .*
  script: main.app
# - url: /
#   static_files: static_files/index.html
#   upload: static_files/index.html
# - url: /(.*\.html)
#   static_files: static_files/\1
#   upload: static_files/.*\.html

libraries:
- name: jinja2
  version: "2.6"
- name: markupsafe
  version: "0.15"
