application: eighty-friends
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /
  static_files: static_files/index.html
  upload: static_files/index.html
- url: /(.*)
  static_files: static_files/\1
  upload: static_files/(.*)
